common/urls.py
# from common.views import index, login, logout  
from common.views import RegisterView, CreateUserProfile, CreateSocUserProfile, ProfileUpdate, SocProfileUpdate  
# from common.views import index, RegisterView, CreateUserProfile  
from django.urls import path  
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy  
from allauth.account.views import login, logout, signup
from common import views


app_name = 'common'  
urlpatterns = [  
    # path('', index, name='index'),  
	# вариант с функциями
	# path('login/', login, name='login'),  
	# path('logout/', logout, name='logout'),
	# вариант с CBV
	# path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	# path('logout/', LogoutView.as_view(), name='logout'),  
	# вариант с гитхабом
    path('profile/', views.profile, name='profile'),
	path('profile/user/<int:pk>/', ProfileUpdate.as_view()),
	# path('profile/socuser/<int:pk>/', SocProfileUpdate.as_view()),
	# path('profile/socuser/<int:pk>/', views.SocProfileUpdate),
	path('profile/socuser/update/', views.SocProfileUpdate),
	path('login/', login, name='login'),  
	path('logout/', logout, name='logout'),
	# path('register/', RegisterView.as_view(  
    #     template_name='register.html',  
	# 	success_url=reverse_lazy('common:profile-create')
	# 	), name='register'),
	path('register/', signup, name='register'),
	path('profile-create/', 
		CreateUserProfile.as_view(), name='profile-create'),
    # path('socprofile-create/', 
	# 	CreateSocUserProfile.as_view(), name='socprofile-create'),    
    path('socprofile-create/', views.CreateSocUserProfile, name='socprofile-create'),  
  
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include  

# from common import views
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  
    path('', include('p_library.urls', namespace='p_library')), # include работает, только если его импортировать
    path('', include('common.urls', namespace='common')),
   
]
  
# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.contrib import admin  
from django.urls import path 
from p_library import views 
from .views import AuthorEdit, FriendEdit, FriendUpdate, FriendDelete, AuthorList, author_create_many, books_authors_create_many, PublisherList

app_name = 'p_library'  

urlpatterns = [

        path('author/create', AuthorEdit.as_view(), name='author_create'), # по .as_view() см. выше Class-based views
        path('authors', AuthorList.as_view(), name='author_list'),
        path('author/create_many', author_create_many, name='author_create_many'),
        path('author_book/create_many', books_authors_create_many, name='author_book_create_many'),
        path('friend/create', FriendEdit.as_view()),
        path('friends/<int:pk>/', FriendUpdate.as_view()),
        path('friends/<int:pk>/delete/', FriendDelete.as_view()),
        path('publishers', PublisherList.as_view(), name='publishers'),
        path('index/', views.index, name='index'),
        path('', views.index),
        path('index/book_increment/', views.book_increment),
        path('index/book_decrement/', views.book_decrement),
        path('friends/', views.friends, name='friends_list'),

]
  

p_library/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    full_name = models.TextField()
    birth_year = models.SmallIntegerField()
    country = models.CharField(max_length=2)

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return "{}, {}".format(self.full_name, self.birth_year)
        # return self.full_name




class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.TextField()
    image = models.ImageField(upload_to='book_img', blank=True, null=True)
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey("Author", on_delete=models.CASCADE)
    publisher = models.ForeignKey("Publisher", on_delete=models.CASCADE, default=None,
                                  blank=True, null=True)
    price = models.DecimalField(default=None, max_digits=10, decimal_places=2)
    copy_count = models.SmallIntegerField(default=1)

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return self.title



class Publisher(models.Model):
    name = models.TextField()
    country = models.CharField(max_length=2)

    class Meta:
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'

    def __str__(self):
        return self.name


class Friend(models.Model):
    name = models.CharField(max_length=100)
    books = models.ManyToManyField("Book", default=None,
                                  blank=True)
    class Meta:
        verbose_name = 'Друг'
        verbose_name_plural = 'Друзья'

    def __str__(self):
        return self.name

p_library/forms.py
from django import forms  
from p_library.models import Author, Book, Friend
  
class AuthorForm(forms.ModelForm):  
    full_name = forms.CharField(widget=forms.TextInput)  
    class Meta:  
        model = Author  
        fields = '__all__'

  
class BookForm(forms.ModelForm): 
    title = forms.CharField(widget=forms.TextInput) 
    class Meta:  
        model = Book  
        fields = '__all__'

class FriendForm(forms.ModelForm): 
    class Meta:  
        model = Friend  
        fields = '__all__'

p_library/views.py
from django.shortcuts import render
# from p_library.models import Author, Book, Publisher
from p_library.models import Author, Book, Publisher, Friend

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect
from p_library.forms import AuthorForm, BookForm, FriendForm
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import formset_factory  
from django.http.response import HttpResponseRedirect


class PublisherList(ListView):
    model = Publisher
    template_name = 'publishers.html'

class AuthorEdit(CreateView):  
    model = Author  
    form_class = AuthorForm  
    success_url = reverse_lazy('p_library:author_list')  
    template_name = 'author_edit.html'  

class AuthorDelete(DeleteView):
    model = Author
    form_class = AuthorForm
    fields = ["full_name", "birth_year", "country"]
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_delete.html'

class AuthorList(ListView):  
    model = Author  
    template_name = 'authors_list.html'

class FriendEdit(CreateView):  
    model = Friend  
    form_class = FriendForm  
    success_url = reverse_lazy('friends_list')  
    template_name = 'friend_edit.html'  


class FriendUpdate(UpdateView):
    model = Friend
    # form_class = FriendForm  
    success_url = reverse_lazy('friends_list')  
    fields = ["name", "books"]
    template_name = 'friend_edit.html'

class FriendDelete(DeleteView):
    model = Friend  
    form_class = FriendForm  
    success_url = reverse_lazy('friends_list')  
    template_name = 'friend_delete.html'  
    fields = ["name", "books"]
  
  

def index(request):
    template = loader.get_template('index.html')
    books = Book.objects.all().order_by('publisher')
    # numbers = range(100)
    biblio_data = {
        "title": "мою библиотеку",
        "books": books,
        # "numbers": numbers
    }
    return HttpResponse(template.render(biblio_data, request))


def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)


def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def publishers(request):
    template = loader.get_template('publishers.html')
    publishers = Publisher.objects.all().order_by('name')
    publisher_data = {
        "publishers": publishers,
    }
    return HttpResponse(template.render(publisher_data, request))

def friends(request):
    template = loader.get_template('friends.html')
    friends = Friend.objects.all().order_by('name')
    friends_data = {
        "friends": friends,
    }
    return HttpResponse(template.render(friends_data, request))





def author_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс,
    # который будет создавать наши формы. Обратите внимание на параметр `extra`, 
    # в данном случае он равен двум, это значит, что на странице с несколькими формами 
    # изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST
        # запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #
        #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. 
        # Обратите внимание на параметр `prefix`. Мы можем иметь на странице не только 
        # несколько форм, но и разных формсетов, этот параметр позволяет их отличать в 
        # запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто 
        # "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и
        # ниже передаём его в контекст шаблона.
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

def books_authors_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  
    BookFormSet = formset_factory(BookForm, extra=2)  
    if request.method == 'POST':  
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')  
        if author_formset.is_valid() and book_formset.is_valid():  
            for author_form in author_formset:  
                author_form.save()  
            for book_form in book_formset:  
                book_form.save()  
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  
    else:  
        author_formset = AuthorFormSet(prefix='authors')  
        book_formset = BookFormSet(prefix='books')  
    return render(
        request,  
        'manage_books_authors.html',  
        {  
            'author_formset': author_formset,  
            'book_formset': book_formset,  
        }  
    )

p_library/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% block title %}
        {% endblock %}

        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'p_library:index' %}">Домашняя библиотека</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'p_library:author_list' %}">Авторы <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'p_library:publishers' %}">Издатели</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'p_library:friends_list' %}">Должники</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:profile' %}">Профиль пользователя {{ user }}</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="#">{{ user }}</a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:logout' %}">Выход</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:login' %}">Вход</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:register' %}">Регистрация</a>
            </li>
            {% endif %}



            <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li> -->
          </ul>

        </div>
      </nav>













    
        {% block content %}
        {% endblock %}
    </body>
    </html>