common/urls.py
# from common.views import index, login, logout  
from common.views import RegisterView, CreateUserProfile, CreateSocUserProfile, ProfileUpdate, SocProfileUpdate  
# from common.views import index, RegisterView, CreateUserProfile  
from django.urls import path  
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy  
from allauth.account.views import login, logout, signup
from common import views


app_name = 'common'  
urlpatterns = [  
    # path('', index, name='index'),  
	# вариант с функциями
	# path('login/', login, name='login'),  
	# path('logout/', logout, name='logout'),
	# вариант с CBV
	# path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	# path('logout/', LogoutView.as_view(), name='logout'),  
	# вариант с гитхабом
    path('profile/', views.profile, name='profile'),
	path('profile/user/<int:pk>/', ProfileUpdate.as_view()),
	# path('profile/socuser/<int:pk>/', SocProfileUpdate.as_view()),
	# path('profile/socuser/<int:pk>/', views.SocProfileUpdate),
	path('profile/socuser/update/', views.SocProfileUpdate),
	path('login/', login, name='login'),  
	path('logout/', logout, name='logout'),
	# path('register/', RegisterView.as_view(  
    #     template_name='register.html',  
	# 	success_url=reverse_lazy('common:profile-create')
	# 	), name='register'),
	path('register/', signup, name='register'),
	path('profile-create/', 
		CreateUserProfile.as_view(), name='profile-create'),
    # path('socprofile-create/', 
	# 	CreateSocUserProfile.as_view(), name='socprofile-create'),    
    path('socprofile-create/', views.CreateSocUserProfile, name='socprofile-create'),  
  
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include  

# from common import views
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  
    path('', include('p_library.urls', namespace='p_library')), # include работает, только если его импортировать
    path('', include('common.urls', namespace='common')),
   
]
  
# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.contrib import admin  
from django.urls import path 
from p_library import views 
from .views import AuthorEdit, FriendEdit, FriendUpdate, FriendDelete, AuthorList, author_create_many, books_authors_create_many, PublisherList

app_name = 'p_library'  

urlpatterns = [

        path('author/create', AuthorEdit.as_view(), name='author_create'), # по .as_view() см. выше Class-based views
        path('authors', AuthorList.as_view(), name='author_list'),
        path('author/create_many', author_create_many, name='author_create_many'),
        path('author_book/create_many', books_authors_create_many, name='author_book_create_many'),
        path('friend/create', FriendEdit.as_view()),
        path('friends/<int:pk>/', FriendUpdate.as_view()),
        path('friends/<int:pk>/delete/', FriendDelete.as_view()),
        path('publishers', PublisherList.as_view(), name='publishers'),
        path('index/', views.index, name='index'),
        path('', views.index),
        path('index/book_increment/', views.book_increment),
        path('index/book_decrement/', views.book_decrement),
        path('friends/', views.friends, name='friends_list'),

]
  

common/models.py
from django.db import models
from django.contrib.auth.models import User  
from allauth.socialaccount.models import SocialAccount
# from SocialAccount.fields import JSONField
# import json
# Create your models here.

  
  
class UserProfile(models.Model):  
  
    age = models.IntegerField()  
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', blank=True)
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=20)

common/forms.py
from django import forms  
from common.models import UserProfile
  
  
class ProfileCreationForm(forms.ModelForm):  
  
    class Meta:  
        model = UserProfile  
        fields = ['name', 'age', 'city']
        labels = {'name':'Имя', 'age':'Возраст', 'city':'Город' }


# class ProfileSocAccCreationForm(forms.Form):
#     name = forms.CharField()
#     age = forms.IntegerField()
#     city = forms.CharField()

common/views.py
from django.shortcuts import render  
from django.contrib.auth.forms import AuthenticationForm  
from django.contrib import auth  
from django.http.response import HttpResponseRedirect  
from django.urls import reverse_lazy  
from django.template import loader

from django.views.generic import FormView  
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth import login, authenticate  
from common.forms import ProfileCreationForm
from django.views.generic import  UpdateView

from common.models import UserProfile

from allauth.socialaccount.models import SocialAccount
import uuid
  


def profile(request):  
    context = {}  
    if request.user.is_authenticated:  
        context['username'] = request.user.username
        try:
            soc_user = SocialAccount.objects.get(provider='github', user=request.user)
            try:
                context['name'] = SocialAccount.objects.get(provider='github', user=request.user).extra_data['name']
                context['age'] = SocialAccount.objects.get(provider='github', user=request.user).extra_data['age']
                context['city'] = SocialAccount.objects.get(provider='github', user=request.user).extra_data['city']
                context['github_url'] = SocialAccount.objects.get(provider='github', user=request.user).extra_data['html_url']
                context['id'] = SocialAccount.objects.get(provider='github', user=request.user).extra_data['id']     

                return render(request, 'profile.html', context)
                
            except KeyError:
                return HttpResponseRedirect(reverse_lazy('common:socprofile-create'))

        except SocialAccount.DoesNotExist:
            try:
                context['name'] = UserProfile.objects.get(user=request.user).name
                context['age'] = UserProfile.objects.get(user=request.user).age
                context['city'] = UserProfile.objects.get(user=request.user).city
                context['id'] = UserProfile.objects.get(user=request.user).id
            except UserProfile.DoesNotExist:
                return HttpResponseRedirect(reverse_lazy('common:profile-create'))

    return render(request, 'profile.html', context)


class RegisterView(FormView):  
  
    form_class = UserCreationForm  
  
    def form_valid(self, form):  
        form.save()  
        username = form.cleaned_data.get('username')  
        raw_password = form.cleaned_data.get('password1')  
        login(self.request, authenticate(username=username, password=raw_password))  
        return super(RegisterView, self).form_valid(form)  
  
  
class CreateUserProfile(FormView):

    success_url = reverse_lazy("common:profile")
    form_class = ProfileCreationForm  
    template_name = 'profile-create.html'  
	
    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('common:login'))  
        return super(CreateUserProfile, self).dispatch(request, *args, **kwargs)  
  
    def form_valid(self, form):  
        instance = form.save(commit=False)  
        instance.user = self.request.user  
        instance.save()  
        return super(CreateUserProfile, self).form_valid(form)


from django.http import HttpResponse
 
def CreateSocUserProfile(request):
    errors = []
    form = {}
    if request.POST:
         
        soc_user = SocialAccount.objects.get(user=request.user)
        a=request.POST.get('name')
        print(a)
        print(soc_user)
        b=soc_user.extra_data
        print(b)

        soc_user.extra_data['name'] = request.POST.get('name')
        soc_user.extra_data['age'] = request.POST.get('age')
        soc_user.extra_data['city'] = request.POST.get('city')
        b['name'] = request.POST.get('name')
        print(b)
        soc_user.save()
        return HttpResponseRedirect(reverse_lazy('common:profile'))

    return render(request, 'profile-create-soc.html')
         

def SocProfileUpdate(request):
    errors = []
    form = {}
    if request.POST:
         
        soc_user = SocialAccount.objects.get(user=request.user)
        soc_user.extra_data['name'] = request.POST.get('name')
        soc_user.extra_data['age'] = request.POST.get('age')
        soc_user.extra_data['city'] = request.POST.get('city')
        soc_user.save()
        return HttpResponseRedirect(reverse_lazy('common:profile'))

    return render(request, 'profile-update-soc.html')


class ProfileUpdate(UpdateView):
    model = UserProfile
    form_class = ProfileCreationForm 
    success_url = reverse_lazy('common:profile')  
    template_name = 'profile-update.html'

common/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% block title %}
        {% endblock %}

        <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'p_library:index' %}">Домашняя библиотека</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'p_library:author_list' %}">Авторы <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'p_library:publishers' %}">Издатели</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'p_library:friends_list' %}">Должники</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:profile' %}">Профиль пользователя {{ user }}</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="#">{{ user }}</a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:logout' %}">Выход</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:login' %}">Вход</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:register' %}">Регистрация</a>
            </li>
            {% endif %}
          </ul>

        </div>
      </nav>
    
        {% block content %}
        {% endblock %}
    </body>
    </html>

common/templates/login.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Войти</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{{ form.as_table }}  
	<input type="submit" value="Войти">  
</form>  
</body>  
</html>

common/templates/profile-create-soc.html
    {% extends 'base.html' %}

    {% block content %}
    <br>
    <div class="container-fluid">
    <div class="col-6">
        <h5>Введите дополнительные данные <br> для создания профиля пользователя</h5>
        <br>  

        <form action="" method="post">
            <table>
                <tbody>
                    <tr>
                        <td>Имя</td>
                        <td><input name="name" type="text" value="{{ form.name }}"></td>
                    </tr>
                    <tr>
                        <td>Возраст</td>
                        <td><input name="age" type="text" value="{{ form.age }}"></td>
                    </tr>
                    <tr>
                        <td>Город</td>
                        <td><input name="city">{{ form.city }}</input></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Отправить"></td>
                    </tr>
                </tbody>
            </table>
        {% csrf_token %}
        </form>

    </div>
    </div>  
    {% endblock %}
    
    {% block title %}
        <title>Профиль пользователя</title>  
    {% endblock %}

common/templates/profile-create.html
{% extends 'base/base.html' %}

{% block content %}
<br>
<div class="container-fluid">
<div class="col-6">
    <h5>Введите дополнительные данные <br> для создания профиля пользователя</h5>
    <br>  
    <form method="post">  
    {% csrf_token %}
    <table>
		{{ form }}

    </table> 
    <br>
    

        <input type="submit" value="Создать профиль">  
    </form>
</div>
</div>  
{% endblock %}

{% block title %}
	<title>Профиль пользователя</title>  
{% endblock %}

common/templates/profile-update-soc.html
{% extends 'base/base.html' %}

{% block content %}
<br>
<div class="container-fluid">
<div class="col-6">
    <h5>Изменение данных пользователя</h5>
    <br>  

    <form action="" method="post">
        <table>
            <tbody>
                <tr>
                    <td>Имя</td>
                    <td><input name="name" type="text" value="{{ form.name }}"></td>
                </tr>
                <tr>
                    <td>Возраст</td>
                    <td><input name="age" type="text" value="{{ form.age }}"></td>
                </tr>
                <tr>
                    <td>Город</td>
                    <td><input name="city">{{ form.city }}</input></td>
                </tr>
                <tr>
                    <td colspan="2"><input type="submit" value="Отправить"></td>
                </tr>
            </tbody>
        </table>
    {% csrf_token %}
    </form>

</div>
</div>  
{% endblock %}

{% block title %}
    <title>Профиль пользователя</title>  
{% endblock %}

common/templates/profile-update.html
{% extends 'base/base.html' %}

{% block content %}
<br>
<div class="container-fluid">
<div class="col-6">
    <h5>Изменение данных профиля</h5>
    <br>  
    <form method="post">  
    {% csrf_token %}
    <table>
		{{ form }}

    </table> 
    <br>
    

        <input type="submit" value="Сохранить">  
    </form>
</div>
</div>  
{% endblock %}

{% block title %}
	<title>Профиль пользователя</title>  
{% endblock %}

common/templates/profile.html
{% extends 'base/base.html' %}

{% block content %}
<br>
<div class="container-fluid">
<div class="col-10">

    {% if username %}
        <h2>Профиль пользователя {{ username }}</h2>
        <br>
        <p>Имя: {{ name }} </p>
        <p>Возраст: {{ age }}</p>
        <p>Город: {{ city }}</p>
        {% if github_url %}
            <p>Профиль на Github: <a href="{{ github_url }}">{{ github_url }}</a></p>
            <br>
            <p> <a href="socuser/update/">Изменить профиль</a></p>           
        {% else %} 
            <br>
            <p> <a href="user/{{ id }}/">Изменить профиль</a></p>
        {% endif %} 

        <p>Тут ты можешь <a href="/logout">выйти</a>.</p>  
    {% else %}  

        <p>Тебе нужно <a href="/register">зарегистрироваться</a> или <a href="/login">войти на сайт</a>!</p> 
    {% endif %}  

</div>
</div>  
{% endblock %}


{% block title %}
	<title>Профиль пользователя</title>  
{% endblock %}